name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers and deps
        run: npx playwright install --with-deps

      - name: Build extension
        run: npm run build

      - name: Run tests
        # use the CI-friendly reporter and fail on problems
        run: npm run test:ci
        env:
          EXT_PATH: ${{ github.workspace }}/dist

      - name: Upload Playwright Report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
